# Generated by Django 3.1.5 on 2021-01-15 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20210115_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'get_latest_by': 'new_mileage'},
        ),
    ]
