# Generated by Django 3.1.5 on 2021-01-15 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210115_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='mileage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tracker.logs'),
        ),
    ]
